"""projects table

Revision ID: 92f7f522d065
Revises: cee2e3fec91a
Create Date: 2020-01-26 03:37:02.550497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f7f522d065'
down_revision = 'cee2e3fec91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_Id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'user_Id')
    # ### end Alembic commands ###
