"""projects table

Revision ID: f07d5ead465f
Revises: 92f7f522d065
Create Date: 2020-01-26 03:38:09.649218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07d5ead465f'
down_revision = '92f7f522d065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project', 'user', ['user_Id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    # ### end Alembic commands ###
